### ISSUE TITLE
НМС АААААА

### ISSUE THREAD

**Issue by Anyachkaa** [yasha-java/ParticleLib#1]
Качать BuildTools -> Загружать 1.20 исходники -> пилить это все в maven.xml -> искать исправление билда ClassNotFined (Лучше ProtocolLib)
Если проект в открытом доступе, пиши инструкцию. Пон?

**Comment by Anyachkaa** [comment]
Конечно пакеты это - крута!

**Comment by Anyachkaa** [comment]
У того же самого By1337 все написано что и как
![image](https://github.com/LinyDevelopment/ParticleLib/assets/151891194/470d2719-163e-49a4-bfc8-c5541f0c1b80)
https://github.com/By1337/BAuction/blob/master/README.md

**Comment by yasha-java** [comment]
> Качать BuildTools -> Загружать 1.20 исходники -> пилить это все в maven.xml -> искать исправление билда ClassNotFined (Лучше ProtocolLib) Если проект в открытом доступе, пиши инструкцию. Пон?

Так ну для начала, проект этот как бы не имеет большого потенциала и был загружен в паблик потому что друзья\коллеги будут юзать. Если человеку надо - разбереться
